shopproject/shopproject/searchapp/urls.py
from django.urls import path
from . import views

app_name = 'searchapp'
urlpatterns = [
    path('', views.SearchResult, name='SearchResult'),

]

shopproject/shopproject/shopapp/urls.py
from django.urls import path

from . import views
app_name='shopapp'
urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail')

]

shopproject/shopproject/shopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shopapp.urls')),
    path('search/',include('searchapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shopproject/shopproject/searchapp/models.py
from django.db import models

# Create your models here.

shopproject/shopproject/shopapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return  reverse('shopapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='category', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shopapp:prodCatdetail',args=[self.category.slug,self.slug])


    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    def __str__(self):
        return '{}'.format(self.name)

shopproject/shopproject/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q
# Create your views here.
def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

shopproject/shopproject/shopapp/views.py
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from . models import Category,Product
# Create your views here.
def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page',1))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products})
def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

shopproject/shopproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'header.html' %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

shopproject/shopproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
    {{category.description|truncatewords:155}}
    {% else %}
        welcome to happycart where you can buy anything
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
    {{category.name}}-HAPPYCART store..
    {% else %}
        see our new collections
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
            <p><a href="{% url 'shopapp:allProdCat' %}">our product collection</a></p>
        </div>
            </div>
    </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
    {% else %}
<div>
    <img class="my_image my_image-padding" src="{% static 'img/banner.png' %}" alt="our products" width="100%" height="350px">
</div>
<br>
<div>
    <h1 class="text-center my_title">our products collections</h1>
    <p class="text-justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

    </p>
</div>
    {% endif %}
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4 ">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top " src="{{product.image.url}}" alt="{{product.name}}"</a>
            <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>{{product.price}}</p>
            </div>
         </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>

    </div>
        {% endif %}
</div>
{% endblock %}

shopproject/shopproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;happycart pvt ltd.All Right Reserved</p>
</div>

shopproject/shopproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shopapp:allProdCat' %}"><img src="{% static 'img/logo.jpg' %}" alt="logimage"></a >
    </center>
</header>

shopproject/shopproject/templates/index.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shopapp:allProdCat' %}">Allction</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}55</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link href="#">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>




































--------------------------------------------------------------------------------------------------------------
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'shopapp:allProdCat' %}">All 25255555roducts</a>
                {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
                {% endfor %}

        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">your cart()</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

</nav>

shopproject/shopproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shopapp:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}

          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><i class="fa fa-shopping-cart" ></i></a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:SearchResult' %}" method="get">
          {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" ></i></button>
      </form>
    </div>
  </div>
</nav>

shopproject/shopproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
    {% if category %}
    {{product.name}}-HAPPYCART store..
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shopapp:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>

    </div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
         <img src="{{product.image.url}}" alt="{{product.name}}">
    </div>
</div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
        <h1 class="my_prod_title_">{{product.name}}</h1>
        <p>{{product.price}}</p>
        <p class="my_title">Product Description</p>
        <p class="text-justify my_rod-text">{{product.description}}</p>
        {% if product.stock <= 0 %}
            <p class="text-justify my_prod-text"><b>Out Of Stock</b></p>
        {% else %}
        <a class="btn- btn-secondary" href="">Add to cart</a>
        {% endif %}
        </div>
    </div>
 </div>
</div>
</div>
{% endblock %}

shopproject/shopproject/templates/search.html
% extends 'base.html' %}
{% load static %}
{% block metadescription %}

     we have variety of products.
{% endblock %}
{% block title %}

search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4 ">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top " src="{{product.image.url}}" alt="{{product.name}}"</a>
            <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>{{product.price}}</p>

            </div>
         </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}